==== Ansible Advanced Homework

1. Create 2 Lab environments
  - OPENTLC Automation -> Ansible Advanced - Homework 
  - OPENTLC Automation -> Ansible Advanced - OpenStack

2. Copy and set the permissions of the /root/.ssh/mykey.pem file to 0400 and set the owner as root:root.

    laptop]# scp -i /home/<username>/.ssh/your-key.pem /home/<username>/.ssh/your-key.pem username-company.name@bastion.<GUID>.example.com:/tmp
    laptop]# ssh -i /home/<username>/.ssh/your-key.pem  username-company.name@bastion.<GUID>.example.com
    bastion]$  sudo -i
    bastion]# cp /tmp/<your-key.pem>  /root/.ssh/mykey.pem
    bastion]# chown root:root /root/.ssh/mykey.pem
    bastion]# chmod 0400 /root/.ssh/mykey.pem

3. Verify a successful connection to workstation-${OSP_GUID}.rhpds.opentlc.com using ~/.ssh/mykey.pem:

    bastion]$ sudo -i
    bastion]# ssh -i /root/.ssh/mykey.pem <username-company.com>@workstation-${OSP_GUID}.rhpds.opentlc.com
    workstation]$ exit
    bastion]#

4. Fork the github repo 

    bastion]# git clone https://github.com/prasanna-holla/ansible_advance_homework
    bastion]# cd ansible_advance_homework

5. edit the environment_setup.sh for following variables

	TOWER_GUID=
	OSP_GUID=
	OPENTLC_LOGIN=prasanna.holla-in.ibm.com
	OPENTLC_PASSWORD=
	GITHUB_REPO=https://github.com/prasanna-holla/ansible_advance_homework
	RH_MAIL_ID=prasanna.holla@in.ibm.com

6. Run the environment_setup script to setup workstation, isolated node, OSP components and configure tower

   bastion]# bash environment_setup.sh 

7. Using following credentials log in to Ansible Tower nodes:

    URL	- https://tower(1-3).{{TOWER_GUID}}.example.opentlc.com
    Username - Admin
    Password - r3dh4t1!


8. In Tower UI, verify following
    a. In "Instance Groups" section, verify Isolated node with ensure "osp" entry exists.
    b. Under "Projects" section, verify "Homework Assignment" project exists
    c. Under "Templates" section, you can locate multiple entries. 

9. Execute "cicd_workflow" by clicking on rocket symbol. This should create QA & Prod environments, deploy 3-tier apps and test them.

10. In bastion server, run grading-script.yml playbook for verifying successful completion of the homework

    bastion]# export ANSIBLE_ADVANCE_GUID=<GUID of 3tier-lab created using order_svc.sh script>
    bastion]# export OSP_GUID=<osp guid>    
	bastion]# cd /root/ansible_advance_homework
    bastion]# ansible-playbook grading-script.yml -e OSP_GUID=${OSP_GUID} -e ANSIBLE_ADVANCE_GUID=${ANSIBLE_ADVANCE_GUID}

.List of Playbooks
[%header,cols=2*]
|===
| Files or dir | Purpose
| app-tier | Install application server role
| db-tier  | Install postgres sql server for database role
| lb-tier  | Install HA proxy role
| base-config | Setup yum repo and base packages role
| setup-workstation | Setup workstation, openstack related tools role 
| setup-openstack | Setup openstack components such as create network, ssh keypair, security group etc. role 
| osp-instance-create | Provision OSP Instances role
| osp-instance-delete | Delete OSP Instances role
| osp-facts | Generate in-memory inventory for OSP instances role
| roles/config-tower/vars/main.yml | Very important file to review. All the variable values are set there. Please do not make any changes in the file
| config-tower | Role to configure ansible tower job templates and workflow
| aws_creds.yml | Fetch GUIDkey.pem from bastion of Three tier application env and create machine credential to connect to AWS instances
| aws_provision.yml | Use `order_svc.sh` script to provision env
| aws_status_check.yml | Check aws instances are up or not
| site-3tier-app.yml | Playbook to deploy three tier app
| site-install-isolated-node.yml | Playbook to install isolated node
| site-config-tower.yml | Playbook to call role `config-tower`
| site-osp-delete.yml | Playbook to call `osp-instance-delete` role
| site-osp-instances.yml | Playbook to call `osp-instance-create` role
| site-setup-workstation.yml | Playbook to call `setup-workstation` role
| site-setup-openstack.yml | Playbook to call `setup-openstack` role
| site-smoke-osp.yml | Playbook to test three tier app on OSP
| site-smoketest-aws.yml | Playbook to test three tier app on AWS
| grading-script.yml | Self grading script
| roles/config-tower/tasks/ec2_dynamic.yml | For creating Dynamic inventory in Ansible tower. Use `AWS Access Key` for credential
| roles/config-tower/tasks/job_template.yml | For creating job templates
| roles/config-tower/tasks/pre-config-tower.yml | Any pre config tasks needed
| roles/config-tower/tasks/workflow_template.yml | genrate workflow from `workflow.yml` file
| roles/config-tower/tasks/post-config-tower.yml | any post config jobs
|===
